# Generated by Django 6.0.4 on 2026-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(default='+258 84 000 0000', max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(default='258840000000', max_length=20, verbose_name='WhatsApp (número com código)')),
                ('email', models.EmailField(default='cassimo@refrigeracao.com', max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(default='Maputo - Moçambique', max_length=200, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Informação de Contato',
                'verbose_name_plural': 'Informação de Contato',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Especialista em Ar-Condicionado e Refrigeração em Maputo', max_length=200, verbose_name='Título')),
                ('subtitulo', models.TextField(default='Instalação, manutenção, reparação e recarga de gás...', verbose_name='Subtítulo')),
                ('botao_texto', models.CharField(default='Solicitar Orçamento', max_length=50, verbose_name='Texto do botão')),
                ('botao_link', models.CharField(default='#contato', max_length=200, verbose_name='Link do botão')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título/Alt')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Rede social')),
                ('url', models.URLField(verbose_name='Link')),
                ('icone', models.CharField(default='fab fa-facebook', max_length=50, verbose_name='Classe do ícone')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='fas fa-wrench', max_length=50, verbose_name='Classe do ícone (FontAwesome)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do serviço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre mim', max_length=100, verbose_name='Título da seção')),
                ('texto', models.TextField(verbose_name='Texto principal')),
                ('icone_diferencial', models.CharField(default='fas fa-check-circle', max_length=50, verbose_name='Ícone dos diferenciais')),
                ('diferenciais', models.TextField(help_text='Exemplo:\nDiagnóstico rápido\nPeças originais', verbose_name='Lista de diferenciais (um por linha)')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
    ]
