# Generated by Django 6.0.4 on 2026-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contatoinfo_herosection_imagemgaleria_redesocial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('tipo_servico', models.CharField(choices=[('instalacao', 'Instalação de Ar-Condicionado'), ('manutencao', 'Manutenção Preventiva'), ('reparacao', 'Reparação/Conserto'), ('limpeza', 'Limpeza de equipamentos'), ('recarga', 'Recarga de Gás'), ('outros', 'Outros serviços')], max_length=50, verbose_name='Tipo de serviço')),
                ('tipo_equipamento', models.CharField(blank=True, choices=[('split', 'Ar-Condicionado Split'), ('cassete', 'Ar-Condicionado Cassete'), ('piso_teto', 'Piso-Teto'), ('janela', 'Ar-Condicionado de Janela'), ('camara_fria', 'Câmara Fria'), ('freezer', 'Freezer/Refrigerador'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo de equipamento')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade de equipamentos')),
                ('descricao', models.TextField(verbose_name='Descrição detalhada do serviço')),
                ('data_preferencial', models.DateField(blank=True, null=True, verbose_name='Data preferencial para atendimento')),
                ('horario_preferencial', models.CharField(blank=True, choices=[('manha', 'Manhã (8h-12h)'), ('tarde', 'Tarde (13h-17h)'), ('noite', 'Noite (18h-21h)'), ('qualquer', 'Qualquer horário')], max_length=50, verbose_name='Horário preferencial')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('viewed', 'Visualizado'), ('contacted', 'Em contato'), ('budget_sent', 'Orçamento enviado'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('completed', 'Concluído')], default='pending', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações da equipe sobre este orçamento', verbose_name='Observações internas')),
                ('valor_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do orçamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de visualização')),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contatoinfo',
            name='email',
            field=models.EmailField(default='cassimosaize@refrigeracao.com', max_length=254, verbose_name='E-mail'),
        ),
    ]
